### PR TITLE
Deprecated the use of require_once

### PR DESCRIPTION
**Pull request by Meneth**
Now all code paths use extension registration.
This is a breaking change for wikis under 1.25. Wikis 1.25+ will continue to work even if they continue using the old access point.

The big advantage is that now only a single code path has to be maintained.
You might want expand the README file to cover all the settings, as JSON doesn't support comments so the extension registration file can't explain what anything does.

### CODE REVIEW

**Comment by kulttuuri** [comment]
Fantastic. Merging in! 👍

**Comment by kulttuuri** [comment]
"You might want expand the README file to cover all the settings, as JSON doesn't support comments so the extension registration file can't explain what anything does."

Hmm, are there currently some settings that are not in the README file?

**Comment by Meneth** [comment]
Might've been just my imagination. I'll make sure to take another look just to make sure.

**Comment by kulttuuri** [comment]
Great. I'll also up the version number to 1.5 now and update mediawiki extension article to reflect this change

**Comment by Meneth** [comment]
Right, missing settings documentation:
wgWikiUrlEndingDiff
wgSlackIncludeDiffSize

**Comment by kulttuuri** [comment]
OK - Readme updated.

**Pull request merged**
