### PR TITLE
Use MW extension registration

### PR DESCRIPTION
**Pull request by Meneth**
Thought it'd make sense to update the extension to use [MW's extension registration system](https://www.mediawiki.org/wiki/Manual:Extension_registration), since the old style the extension currently uses is deprecated.

The old entry point still works as well.

Biggest change is that I moved out all the code to SlackNotificationsCore, and made that a class so that the registration system's AutoLoadClass functionality would work.

$wgSlackFromName now also defaults to blank, but then uses the sitename if it hasn't been set to anything. Should cause no actual change, but was necessary since it is AFAIK not possible to reference variables in the extension registration itself.

### CODE REVIEW

**Comment by kulttuuri** [comment]
Looks like my response by email didn't go through here. But yes, this is fantastic. I've noticed this format on like beginning of this year but didn't implement it yet at that time. I'll try to dedicate time today / tomorrow to test this feature and push it live after that :)

**Comment by Meneth** [comment]
Great to hear.

Going by [WikiApiary](https://wikiapiary.com/wiki/Extension:Slack_Notifications), there's only a single wiki using the extension that isn't up to date enough to use the extension registration functionality, so you might want to consider deprecating the old activation method so that you don't have to maintain two access points.

The [MW page about registration](https://www.mediawiki.org/wiki/Manual:Extension_registration#Migration_for_extension_developers) has info on how to deprecate the access point in a way that only breaks it for wikis below MW 1.25.

**Comment by kulttuuri** [comment]
Alright! Finally got the chance to test this out. Seems to be working well. Merging in :)

How does the access point work in your latest commit?

**Comment by Meneth** [comment]
Currently, either will work:
wfLoadExtension('SlackNotifications');
or
require_once "$IP/extensions/SlackNotifications/SlackNotifications.php";

And will work even before 1.25.
If you want to deprecate the old access point so people switch over, see the page I linked above. I can make another PR for that if you want.
Note that that'd break it for anyone below MW 1.25 if they update. Though what the chances are that someone will update the extension when they're on such an unsupported MW version (unless they're on 1.23 LTS, I suppose) I don't know.

**Comment by kulttuuri** [comment]
Yeah, let's switch over to new format. If someone updates their wiki to new version they probably are getting that error also for any other old extension they have.

**Comment by Meneth** [comment]
Will make a PR for it soon, then!

**Pull request merged**
